/// <reference path="../bower_components/DefinitelyTyped/requirejs/require.d.ts" />
/// <reference path="../bower_components/DefinitelyTyped/angularjs/angular.d.ts" />
require.config({
    paths: {
        css: '/bower_components/require-css/css',
        async: '/bower_components/requirejs-plugins/src/async',
        depend: '/bower_components/requirejs-plugins/src/depend',
        font: '/bower_components/requirejs-plugins/src/font',
        goog: '/bower_components/requirejs-plugins/src/goog',
        image: '/bower_components/requirejs-plugins/src/image',
        json: '/bower_components/requirejs-plugins/src/json',
        mdown: '/bower_components/requirejs-plugins/src/mdown',
        noext: '/bower_components/requirejs-plugins/src/noext',
        propertyParser: '/bower_components/requirejs-plugins/src/propertyParser',
        autocomplete: '/bower_components/material/src/components/autocomplete/autocomplete',
        backdrop: '/bower_components/material/src/components/backdrop/backdrop',
        bottomSheet: '/bower_components/material/src/components/bottomSheet/bottomSheet',
        button: '/bower_components/material/src/components/button/button',
        card: '/bower_components/material/src/components/card/card',
        checkbox: '/bower_components/material/src/components/checkbox/checkbox',
        chips: '/bower_components/material/src/components/chips/chips',
        content: '/bower_components/material/src/components/content/content',
        datepicker: '/bower_components/material/src/components/datepicker/datepicker',
        dialog: '/bower_components/material/src/components/dialog/dialog',
        divider: '/bower_components/material/src/components/divider/divider',
        fabActions: '/bower_components/material/src/components/fabActions/fabActions',
        fabSpeedDial: '/bower_components/material/src/components/fabSpeedDial/fabSpeedDial',
        fabToolbar: '/bower_components/material/src/components/fabToolbar/fabToolbar',
        fabTrigger: '/bower_components/material/src/components/fabTrigger/fabTrigger',
        gridList: '/bower_components/material/src/components/gridList/gridList',
        icon: '/bower_components/material/src/components/icon/icon',
        input: '/bower_components/material/src/components/input/input',
        list: '/bower_components/material/src/components/list/list',
        menu: '/bower_components/material/src/components/menu/menu',
        menuBar: '/bower_components/material/src/components/menuBar/menuBar',
        progressCircular: '/bower_components/material/src/components/progressCircular/progressCircular',
        progressLinear: '/bower_components/material/src/components/progressLinear/progressLinear',
        radioButton: '/bower_components/material/src/components/radioButton/radioButton',
        select: '/bower_components/material/src/components/select/select',
        showHide: '/bower_components/material/src/components/showHide/showHide',
        sidenav: '/bower_components/material/src/components/sidenav/sidenav',
        slider: '/bower_components/material/src/components/slider/slider',
        sticky: '/bower_components/material/src/components/sticky/sticky',
        subheader: '/bower_components/material/src/components/subheader/subheader',
        swipe: '/bower_components/material/src/components/swipe/swipe',
        switch: '/bower_components/material/src/components/switch/switch',
        tabs: '/bower_components/material/src/components/tabs/tabs',
        toast: '/bower_components/material/src/components/toast/toast',
        toolbar: '/bower_components/material/src/components/toolbar/toolbar',
        tooltip: '/bower_components/material/src/components/tooltip/tooltip',
        virtualRepeat: '/bower_components/material/src/components/virtualRepeat/virtualRepeat',
        whiteframe: '/bower_components/material/src/components/whiteframe/whiteframe',
        autocompleteCss: '/bower_components/angular-material-sass-files/components/autocomplete',
        backdropCss: '/bower_components/angular-material-sass-files/components/backdrop',
        bottomSheetCss: '/bower_components/angular-material-sass-files/components/bottom-sheet',
        buttonCss: '/bower_components/angular-material-sass-files/components/button',
        cardCss: '/bower_components/angular-material-sass-files/components/card',
        checkboxCss: '/bower_components/angular-material-sass-files/components/checkbox',
        chipsCss: '/bower_components/angular-material-sass-files/components/chips',
        contentCss: '/bower_components/angular-material-sass-files/components/content',
        calendarCss: '/bower_components/angular-material-sass-files/components/calendar',
        datepickerCss: '/bower_components/angular-material-sass-files/components/datepicker',
        dialogCss: '/bower_components/angular-material-sass-files/components/dialog',
        dividerCss: '/bower_components/angular-material-sass-files/components/divider',
        fabSpeedDialCss: '/bower_components/angular-material-sass-files/components/fabSpeedDial',
        fabToolbarCss: '/bower_components/angular-material-sass-files/components/fabToolbar',
        gridListCss: '/bower_components/angular-material-sass-files/components/grid-list',
        iconCss: '/bower_components/angular-material-sass-files/components/icon',
        inputCss: '/bower_components/angular-material-sass-files/components/input',
        listCss: '/bower_components/angular-material-sass-files/components/list',
        menuCss: '/bower_components/angular-material-sass-files/components/menu',
        menuBarCss: '/bower_components/angular-material-sass-files/components/menu-bar',
        progressCircularCss: '/bower_components/angular-material-sass-files/components/progress-circular',
        progressLinearCss: '/bower_components/angular-material-sass-files/components/progress-linear',
        radioButtonCss: '/bower_components/angular-material-sass-files/components/radio-button',
        selectCss: '/bower_components/angular-material-sass-files/components/select',
        sidenavCss: '/bower_components/angular-material-sass-files/components/sidenav',
        sliderCss: '/bower_components/angular-material-sass-files/components/slider',
        stickyCss: '/bower_components/angular-material-sass-files/components/sticky',
        subheaderCss: '/bower_components/angular-material-sass-files/components/subheader',
        switchCss: '/bower_components/angular-material-sass-files/components/switch',
        tabsCss: '/bower_components/angular-material-sass-files/components/tabs',
        toastCss: '/bower_components/angular-material-sass-files/components/toast',
        toolbarCss: '/bower_components/angular-material-sass-files/components/toolbar',
        tooltipCss: '/bower_components/angular-material-sass-files/components/tooltip',
        virtualRepeaterCss: '/bower_components/angular-material-sass-files/components/virtual-repeater',
        whiteframeCss: '/bower_components/angular-material-sass-files/components/whiteframe',
        layout: '/bower_components/angular-material-sass-files/components/layout.scss',
        modernizr: '/bower_components/modernizr/src/Modernizr',
        angular: '/bower_components/angular/angular',
        angularAnimate: '/bower_components/angular-animate/angular-animate',
        angularAria: '/bower_components/angular-aria/angular-aria',
        angularMessages: '/bower_components/angular-messages/angular-messages',
        angularMaterial: '/bower_components/angular-material/angular-material',
        SiteCss: '/css/Site',
        Site: '/js/Site',
        Bootstrap: '/js/Bootstrap',
    },
    shim: {
        autocomplete: { deps: ['angular', 'css!autocompleteCss'] },
        backdrop: { deps: ['angular', 'css!backdropCss'] },
        bottomSheet: { deps: ['angular', 'css!bottomSheetCss'] },
        button: { deps: ['angular', 'css!buttonCss'] },
        card: { deps: ['angular', 'css!cardCss'] },
        checkbox: { deps: ['angular', 'css!checkboxCss'] },
        chips: { deps: ['angular', 'css!chipsCss'] },
        content: { deps: ['angular', 'css!contentCss'] },
        datepicker: { deps: ['angular', 'css!calendarCss', 'css!datepickerCss'] },
        dialog: { deps: ['angular', 'css!dialogCss'] },
        divider: { deps: ['angular', 'css!dividerCss'] },
        fabActions: { deps: ['angular', 'css!fabActionsCss'] },
        fabSpeedDial: { deps: ['angular', 'css!fabSpeedDialCss'] },
        fabToolbar: { deps: ['angular', 'css!fabToolbarCss'] },
        fabTrigger: { deps: ['angular', 'css!fabTriggerCss'] },
        gridList: { deps: ['angular', 'css!gridListCss'] },
        icon: { deps: ['angular', 'css!iconCss'] },
        input: { deps: ['angular', 'css!inputCss'] },
        list: { deps: ['angular', 'css!listCss'] },
        menu: { deps: ['angular', 'css!menuCss'] },
        menuBar: { deps: ['angular', 'css!menuBarCss'] },
        progressCircular: { deps: ['angular', 'css!progressCircularCss'] },
        progressLinear: { deps: ['angular', 'css!progressLinearCss'] },
        radioButton: { deps: ['angular', 'css!radioButtonCss'] },
        select: { deps: ['angular', 'css!selectCss'] },
        showHide: { deps: ['angular', 'css!showHideCss'] },
        sidenav: { deps: ['angular', 'css!sidenavCss'] },
        slider: { deps: ['angular', 'css!sliderCss'] },
        sticky: { deps: ['angular', 'css!stickyCss'] },
        subheader: { deps: ['angular', 'css!subheaderCss'] },
        swipe: { deps: ['angular', 'css!swipeCss'] },
        switch: { deps: ['angular', 'css!switchCss'] },
        tabs: { deps: ['angular', 'css!tabsCss'] },
        toast: { deps: ['angular', 'css!toastCss'] },
        toolbar: { deps: ['angular', 'css!toolbarCss'] },
        tooltip: { deps: ['angular', 'css!tooltipCss'] },
        virtualRepeat: { deps: ['angular', 'css!virtualRepeatCss'] },
        whiteframe: { deps: ['angular', 'css!whiteframeCss'] },
        angularAnimate: { deps: ['angular'] },
        angularAria: { deps: ['angular'] },
        angularMessages: { deps: ['angular'] },
        angularMaterial: { deps: ['angular', 'angularAnimate', 'angularAria', 'angularMessages'] },
        Site: { deps: ['angularMaterial', 'css!SiteCss'] },
    }
});
require.config({
    baseUrl: '',
    waitSeconds: 0,
});
require([
    'angular',
    'Site',
], function (ng) {
    ng.element('body').removeClass('hidden');
});
